on:
  push:
    branches:
    - main
    - 'release/**'
  pull_request:
    branches:
    - main
    - 'release/**'

jobs:
  nodejs:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'
    
    - uses: rhosys/github-action-rebuild-pull-requests@v0.1
      # with:
      #   github_token: ${{ secrets.GITHUB_TOKEN }}